### ISSUE TITLE
libjpg error <Solved> Needs to be implemented on your end.

### ISSUE THREAD

**Issue by The-Maize** [MyHCel/Maya-For-Arch#2]
Inside of dependencies.sh
replace ibjpeg     ---->   libjpeg. i have done it on my end that solves one minor bug,

Thanks for the great work im dying to get this working im loosing hand over foot at the moment with work and uni because i cant get it to install. lol. so heres to get it going ! haha cheers mate!

**Comment by MyHCel** [comment]
Thanks for noticing c:
I just fixed it. I guess I need to clean my keyboard.
I really hope I can get this working again.

With this, I'll be closing the issue. Thanks again.
