### ISSUE TITLE
Cannot import maya.standalone library from mayapy

### ISSUE THREAD

**Issue by uikokahonia** [MyHCel/Maya-For-Arch#8]
Hello there,

Thank you very much for taking the time to write this script and sharing it, it worked perfectly fine on EndeavourOS Artemis Neo and Maya 2023.
As you may know, you can run the Maya Python interpreter outside of an instance of the Maya GUI, you do so by executing the file: `/usr/autodesk/maya/bin/mayapy`

That will open the maya python interpreter in your terminal, where you are supposed to be able to import the maya.standalone library by issuing the line `import maya.standalone`. But doing this throws an import error.

`>>> import maya.standalone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libjbig.so.2.1: cannot open shared object file: No such file or directory
`

I tried installing this package: https://aur.archlinux.org/packages/libjbig-shared
But no luck, do you have any insight on this?

Thank you!

**Comment by fislysandi** [comment]
hey does maya still work for you seems like latest glibc update broke it.

**Comment by uikokahonia** [comment]
> hey does maya still work for you seems like latest glibc update broke it.

Maya GUI works for me yup. Well it boots and seems to work, but I haven't tested all the tools.

**Comment by uikokahonia** [comment]
Apparently that library existed all along in the Maya lib folder, so I can imagine it was not about it being missing, but not being found.

```
$ ls /usr/autodesk//maya2023/lib | grep libj
libjbig85.so.2.1
libjbig.so.2.1
```
And simply doing this did the trick:

```bash
export LD_LIBRARY_PATH=/usr/autodesk/maya2023/lib
```

**Comment by fislysandi** [comment]
hey im just having issues where its just crashes and i dont know what to do.
